### ISSUE TITLE
Crash on About Activity when device rotation

### ISSUE THREAD

**Issue by geniuslittleteddy** [gateship-one/odyssey#201]
# Bug Report

### Version of Odyssey
1.1.18
### Android Version
23
### Device Manufacturer and model
Nexus 6 emulator

### Description
![pic9](https://user-images.githubusercontent.com/67744580/86377647-29896d80-bcbb-11ea-9e4a-28acb2704a68.png)
App crashes on About Activity when device rotation

### Log
```
06-24 13:24:04.894 23247 23247 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver org.gateshipone.odyssey.widget.OdysseyWidgetProvider: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
06-24 13:24:04.894 23247 23247 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3018)
06-24 13:24:04.894 23247 23247 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(ActivityThread.java)
06-24 13:24:04.894 23247 23247 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
06-24 13:24:04.894 23247 23247 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-24 13:24:04.894 23247 23247 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-24 13:24:04.894 23247 23247 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
06-24 13:24:04.894 23247 23247 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-24 13:24:04.894 23247 23247 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
06-24 13:24:04.894 23247 23247 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
06-24 13:24:04.894 23247 23247 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
06-24 13:24:04.894 23247 23247 E AndroidRuntime: 	at org.gateshipone.odyssey.widget.OdysseyWidgetProvider.onReceive(OdysseyWidgetProvider.java)
06-24 13:24:04.894 23247 23247 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3011)
06-24 13:24:04.894 23247 23247 E AndroidRuntime: 	... 8 more
06-24 13:24:04.909  1605  1889 W ActivityManager:   Force finishing activity org.gateshipone.odyssey/.activities.OdysseyAboutActivity
```

**Comment by gnome17** [comment]
I wasn't able to reproduce this issue. 

Anyway why did you test this in an emulator with such an old android version?

Please note that 1.1.18 is not the latest version of odyssey.
